-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

-- Araştırıp uygun bulduğum REGEX email value check constraint değerleri:
-- ^[\w!#$%&''*+/=?`{|}~^-]+(?:\.[\w!#$%&''*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,6}$			// Benim Tercihim
-- >>> IP Adresli emaile doğru validasyon + %99.9 Doğru validasyon (İddiaları bu) https://emailregex.com;
-- (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
-- ^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$			// OWASP Validation Regex Repository
-- ^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$			// HTML input-email (eski)
-- ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$   //HTML5-input(yeni) Ancak süzgeç gibi

BEGIN;

CREATE DOMAIN public.checked_email
    AS character varying(75)
    NOT NULL;

ALTER DOMAIN public.checked_email OWNER TO postgres;

ALTER DOMAIN public.checked_email
    ADD CONSTRAINT email_format CHECK (VALUE ~ '^[\w!#$%&''*+/=?`{|}~^-]+(?:\.[\w!#$%&''*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,6}$');

COMMENT ON DOMAIN public.checked_email
    IS 'email format checkini otomatik yapar';
	
CREATE TABLE public."claims"
(
    id smallint PRIMARY KEY,
    claim character varying(50) UNIQUE NOT NULL
);
COMMENT ON TABLE public."claims"
    IS 'Tüm Usersin alabileceği rol/claim/haklar';

CREATE TABLE public."users"
(
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email checked_email UNIQUE NOT NULL, --PRIMARY KEY ile aynı!
    password bytea NOT NULL,
    "claim_id" smallint REFERENCES public."claims" (id) NOT NULL
);
COMMENT ON TABLE public."users"
    IS 'Tüm kullanıcıların temel sınıfı';


CREATE TABLE public."top_job_categories"
(
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name character varying(50) UNIQUE NOT NULL
);
COMMENT ON TABLE public."top_job_categories"
    IS 'Temel Sınıf İş Kategorileri';

CREATE TABLE public."sub_job_categories"
(
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name character varying(50) UNIQUE NOT NULL
);
COMMENT ON TABLE public."sub_job_categories"
    IS 'Alt Sınıf İş Kategorileri';

CREATE TABLE public."jobs"
(
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"top_job_category_id" integer REFERENCES public."top_job_categories" (id) NOT NULL,
    "sub_job_category_id" integer REFERENCES public."sub_job_categories" (id) NOT NULL,
    "job_name" character varying(50) UNIQUE NOT NULL
);
COMMENT ON TABLE public."sub_job_categories"
    IS 'Genel iş pozisyonları';


CREATE TABLE public."staffs"
(
    "user_id" integer PRIMARY KEY REFERENCES public."users" (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE,
    "tckno" character(11) UNIQUE NOT NULL,
    "first_name" character varying(40) NOT NULL,
    "last_name" character varying(40) NOT NULL,
    "year_of_birth" integer NOT NULL,
    "job_id" integer REFERENCES public."jobs" (id) NOT NULL
);
COMMENT ON TABLE public."staffs"
    IS 'Sistem Personeli';

CREATE TABLE public."job_seekers"
(
    "user_id" integer PRIMARY KEY REFERENCES public."users" (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE,
    "tckno" character(11) UNIQUE NOT NULL,
    "first_name" character varying(40) NOT NULL,
    "last_name" character varying(40) NOT NULL,
    "year_of_birth" integer NOT NULL
);
COMMENT ON TABLE public."job_seekers"
    IS 'İş Arayanlar';

CREATE TABLE public."employers"
(
    "user_id" integer PRIMARY KEY REFERENCES public."users" (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE,
    "company_name" character varying(80) NOT NULL,
    website character varying(80) NOT NULL,
    phone character varying(12) NOT NULL
--	CONSTRAINT webcheck_email_vchar CHECK ("position"(website, "substring"(vchr_email::text, '%@#".*%'::text, '#'::text)) > 0) --email diğer tabloda/subquery SQL yasaklıyor
);
COMMENT ON TABLE public."employers"
    IS 'İş Verenler';
END;